# example 2: on merge to master from pull request (recommended)
name: Bump version
on:
  workflow_run:
    workflows:
      - Lint
      - "Pull request/Push: Run unit test"
    types:
      - completed
  pull_request:
    types:
      - closed
    branches:
      - dev
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        WITH_V: true
        PRERELEASE: true
